[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/start-a-project"
  to = "/start-a-project.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
