import { PlaceholderPage } from "@/components/placeholder-page";

export const metadata = {
  title: "Terms",
  description: "Vail Renovations terms and disclaimer placeholder."
};

export default function TermsPage() {
  return (
    <PlaceholderPage
      eyebrow="Terms"
      title="Terms and disclaimer placeholder."
      body="This route is ready for the full disclaimer language. No estimate, permit, engineering or inspection conclusion is generated by this foundation build."
      primaryHref="/project-request"
      primaryLabel="Start a Project Request"
      secondaryHref="/contact"
      secondaryLabel="Contact Vail"
    />
  );
}
